### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by egillespie** [egillespie/codelab-rails-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://protected-fjord-93241.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/rails-intro/1) criteria:

- [x] a `home` action in a `StaticController` is served to `/`, which shows some content unique to this page
- [x] an `about` action in a `StaticController` is served to `/about`, which shows some content unique to this page
- [x] a `cats` action in a `StaticController` is served to `/cat-pictures`, which shows at least 1 cat picture, then shows the number of cat pictures requested when visiting `/cat-pictures/3` (for 3 cats) or `/cat-pictures/5` (for 5 cats), for example
- [x] well-labeled links to all of the above routes exist on all pages of the app, using path helpers and without including the same code in every view file
- [x] there's some CSS that goes through Rails' asset pipeline that visibly affects every page
- [x] at least 1 helper method is used for some visible effect on at least 1 page

**Comment by chrisvfritz** [comment]
Very nice! :+1: :tada: :balloon: :rocket: :shipit: I see no obvious room for improvement. :smiley: While working on this, did you run into anything that prompted a question or surprised you?

**Comment by egillespie** [comment]
I think the closest I got to being confused was on "Creating your first Rails app." I didn't read the comments in the code blocks so I actually ran `rails new codelab-rails-intro` and then ran `rails new codelab-rails-intro --skip-test-unit`. When I got a weird prompt, I looked at the page again and saw the comment for the first code block said not to run that command.

**Comment by egillespie** [comment]
Hmm, I guess "Adding features with Rails generators" did feel a little long compared to the other parts of the lesson. It didn't bug me, I just remember thinking "Wow, this page is longer than I expected."

**Comment by chrisvfritz** [comment]
@egillespie Good to know! Let me know you think of a way to make that comment clearer or split up the page. :smiley:
